### ISSUE TITLE
can it serve lots of mbtiles？

### ISSUE THREAD

**Issue by linghuam** [urbica/tessella#56]
I have two ".mbtiles"  files，I want to use them at the same time，can you tell me how to do it. Thank you very much!

**Comment by stepankuzmin** [comment]
Hi @linghuam! Thanks for the issue!

Unfortunately, tessella is designed to support only one source. However, you can try something like [tilelive-merge](https://github.com/mojodna/tilelive-merge) to merge multiple sources into one.

**Comment by carlos-mg89** [comment]
@linghuam you can use tippecanoe ( https://github.com/mapbox/tippecanoe ) as well for that. Just need to install it, and then do this:

> tile-join -pk -o combined.mbtiles one.mbtiles another.mbtiles

Then it works really great!
