### ISSUE TITLE
Machine specs for running a map like Europe or Planet

### ISSUE THREAD

**Issue by carlos-mg89** [urbica/tessella#58]
I was wondering what should be the required or recommended specs to run a tessella MBTiles server that has a map of Europe or of the Planet. I mean how much RAM and hard drive / SSD space.

I guess it will depend of the amount of requests as well, so if someone has statistics about lets say a 1,000 users, I could do my own calculations based on that.

**Comment by stepankuzmin** [comment]
Hi! Thanks for posting this. The spec truly depends on the requests and the amount of data you have, so it's hard to say. I'll leave this question as open, so maybe someone will share their insights about it.

**Comment by carlos-mg89** [comment]
Thanks for keeping it open :)

I guess that having statistics from people serving a big MBTiles would be enough. However, I'm just gonna try in my project and see what's the impact in a normal day for my current user base.

**Comment by carlos-mg89** [comment]
Well, I forgot to came back with some actual data. I've been serving a vector MBTiles for the whole Europe area with tessella, and the RAM it requires in my server is about 12.5 GB. It has been quite constant during the whole 2020. Probably there have been ups and downs, but it hasn't varied that much.

The space of my Europe MBTiles is ~ 20GB (it's been some time without updates, and I thing it would be 22-23 GB right now).
