### ISSUE TITLE
Can't get it to recognize URL for pbf

### ISSUE THREAD

**Issue by lsiden** [urbica/tessella#60]
/index.json (and source code) indicate that URL pattern is /z/x/y.pbf which I take to mean "zoom", "lng" and "lat".  I built a mbtiles file for North America.  When I GET /12/-96/32.pbf for example, it returns 404.

I printed the tile pattern.  It's /:z(\d+)/:x(\d+)/:y(\d+):scale(@[12]x)?.:format([\w\.]+)

So how do I get it to return anything besides index.json?  What coordinate system are x and y in?

**Comment by lsiden** [comment]
Guess I have to also run a TileLive server.

**Comment by stepankuzmin** [comment]
Hi @lsiden! The tiles URL scheme is in the [Slippy map tilenames](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) format.

How do you make requests for tiles? Do you use any mapping libraries eg. leaflet or mapbox-gl-js?

**Comment by lsiden** [comment]
I got it figured out. I learned that tile coordinates are different than lat/lng coordinates.  

My real goal is to serve static PNG images and I found a ready-made solution with [tileserver-gl](https://github.com/maptiler/tileserver-gl).  

Thanks for the response. Obviously, I'm a n00bie to serving maps but I'm learning.
